### ISSUE TITLE
lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: ""

### ISSUE THREAD

**Issue by CodeEsthete** [kornilova-l/FlameViewer#42]
How to fix this error?

**Comment by kornilova-l** [comment]
Hi, @CodeEsthete,

Thanks for submitting the issue

What were the steps that caused the error?
Did you run Fierix or this exception was thrown when you wanted to upload file and see flamegraph?

If the error appeared when you run Fierix, you can try to exclude all methods of all classloaders:
open **Tools | Fierix | Configuration** and add following pattern to exclude methods
class name: `*ClassLoader*`
method name: `*`
