### ISSUE TITLE
v0.81 doesn't work with CLion 2018.2.4

### ISSUE THREAD

**Issue by vaibhav1618** [kornilova-l/FlameViewer#43]
[idea.log](https://github.com/kornilova-l/FlameViewer/files/2452595/idea.log)
After installing the plugin on CLion and restarting, I do see this option:  Tools->Open Flameviewer. However, clicking on it doesn't open any GUI to upload the profiler file. PFA the logs from CLion

**Comment by kornilova-l** [comment]
@vaibhav1618 hi,
thanks for submitting issue

I've just tested v0.8.1 with CLion 2018.2.4 on macOS and it worked
Attached log file also does not say anything

What os do you use?
Could you start CLion and open this page in browser: http://localhost:63342/FlameViewer/outgoing-calls?project=uploaded-files (also try 63343 port)?
