### ISSUE TITLE
Filter multiple packages?

### ISSUE THREAD

**Issue by brtubb-patagonia** [kornilova-l/FlameViewer#45]
Is it possible to filter multiple packages at the same time?
It looks like the filtering is handled in Filter.kt, using Regex behind the scenes. Looks like adding a bar ('|') between packages works, but I wanted to make sure this is the correct way to filter.

![image](https://user-images.githubusercontent.com/38335968/48497613-58528780-e7e9-11e8-8165-e04518cbb46b.png)

If this is correct, would a note on this in the README be accepted if I submit a PR with an example?

This is a wonderfully powerful tool. Thank you for writing this excellent piece of software!

**Comment by kornilova-l** [comment]
Hi @brtubb-patagonia,
Thank you for nice feedback!
Yes, it's a regexp except that FlameViewer escapes `.` and `$`, it also replaces `*` with `.*`.
It would be nice if you could add clarification to readme!

**Comment by brtubb-patagonia** [comment]
Thank you @kornilova-l! I'll close this out and submit a PR.
